package com.fintech.erp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BankszamlaszamokAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankszamlaszamokAllPropertiesEquals(Bankszamlaszamok expected, Bankszamlaszamok actual) {
        assertBankszamlaszamokAutoGeneratedPropertiesEquals(expected, actual);
        assertBankszamlaszamokAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankszamlaszamokAllUpdatablePropertiesEquals(Bankszamlaszamok expected, Bankszamlaszamok actual) {
        assertBankszamlaszamokUpdatableFieldsEquals(expected, actual);
        assertBankszamlaszamokUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankszamlaszamokAutoGeneratedPropertiesEquals(Bankszamlaszamok expected, Bankszamlaszamok actual) {
        assertThat(actual)
            .as("Verify Bankszamlaszamok auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankszamlaszamokUpdatableFieldsEquals(Bankszamlaszamok expected, Bankszamlaszamok actual) {
        assertThat(actual)
            .as("Verify Bankszamlaszamok relevant properties")
            .satisfies(a ->
                assertThat(a.getBankszamlaDevizanem()).as("check bankszamlaDevizanem").isEqualTo(expected.getBankszamlaDevizanem())
            )
            .satisfies(a -> assertThat(a.getBankszamlaGIRO()).as("check bankszamlaGIRO").isEqualTo(expected.getBankszamlaGIRO()))
            .satisfies(a -> assertThat(a.getBankszamlaIBAN()).as("check bankszamlaIBAN").isEqualTo(expected.getBankszamlaIBAN()))
            .satisfies(a -> assertThat(a.getStatusz()).as("check statusz").isEqualTo(expected.getStatusz()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankszamlaszamokUpdatableRelationshipsEquals(Bankszamlaszamok expected, Bankszamlaszamok actual) {
        assertThat(actual)
            .as("Verify Bankszamlaszamok relationships")
            .satisfies(a -> assertThat(a.getCeg()).as("check ceg").isEqualTo(expected.getCeg()));
    }
}
