package com.fintech.erp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CegAlapadatokAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCegAlapadatokAllPropertiesEquals(CegAlapadatok expected, CegAlapadatok actual) {
        assertCegAlapadatokAutoGeneratedPropertiesEquals(expected, actual);
        assertCegAlapadatokAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCegAlapadatokAllUpdatablePropertiesEquals(CegAlapadatok expected, CegAlapadatok actual) {
        assertCegAlapadatokUpdatableFieldsEquals(expected, actual);
        assertCegAlapadatokUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCegAlapadatokAutoGeneratedPropertiesEquals(CegAlapadatok expected, CegAlapadatok actual) {
        assertThat(actual)
            .as("Verify CegAlapadatok auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCegAlapadatokUpdatableFieldsEquals(CegAlapadatok expected, CegAlapadatok actual) {
        assertThat(actual)
            .as("Verify CegAlapadatok relevant properties")
            .satisfies(a -> assertThat(a.getCegNev()).as("check cegNev").isEqualTo(expected.getCegNev()))
            .satisfies(a -> assertThat(a.getCegRovidAzonosito()).as("check cegRovidAzonosito").isEqualTo(expected.getCegRovidAzonosito()))
            .satisfies(a -> assertThat(a.getCegSzekhely()).as("check cegSzekhely").isEqualTo(expected.getCegSzekhely()))
            .satisfies(a -> assertThat(a.getAdoszam()).as("check adoszam").isEqualTo(expected.getAdoszam()))
            .satisfies(a -> assertThat(a.getCegjegyzekszam()).as("check cegjegyzekszam").isEqualTo(expected.getCegjegyzekszam()))
            .satisfies(a -> assertThat(a.getCegKozpontiEmail()).as("check cegKozpontiEmail").isEqualTo(expected.getCegKozpontiEmail()))
            .satisfies(a -> assertThat(a.getCegKozpontiTel()).as("check cegKozpontiTel").isEqualTo(expected.getCegKozpontiTel()))
            .satisfies(a -> assertThat(a.getStatusz()).as("check statusz").isEqualTo(expected.getStatusz()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCegAlapadatokUpdatableRelationshipsEquals(CegAlapadatok expected, CegAlapadatok actual) {
        // empty method
    }
}
