package com.fintech.erp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MegrendelesDokumentumokAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegrendelesDokumentumokAllPropertiesEquals(MegrendelesDokumentumok expected, MegrendelesDokumentumok actual) {
        assertMegrendelesDokumentumokAutoGeneratedPropertiesEquals(expected, actual);
        assertMegrendelesDokumentumokAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegrendelesDokumentumokAllUpdatablePropertiesEquals(
        MegrendelesDokumentumok expected,
        MegrendelesDokumentumok actual
    ) {
        assertMegrendelesDokumentumokUpdatableFieldsEquals(expected, actual);
        assertMegrendelesDokumentumokUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegrendelesDokumentumokAutoGeneratedPropertiesEquals(
        MegrendelesDokumentumok expected,
        MegrendelesDokumentumok actual
    ) {
        assertThat(actual)
            .as("Verify MegrendelesDokumentumok auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegrendelesDokumentumokUpdatableFieldsEquals(
        MegrendelesDokumentumok expected,
        MegrendelesDokumentumok actual
    ) {
        assertThat(actual)
            .as("Verify MegrendelesDokumentumok relevant properties")
            .satisfies(a -> assertThat(a.getDokumentumTipusa()).as("check dokumentumTipusa").isEqualTo(expected.getDokumentumTipusa()))
            .satisfies(a -> assertThat(a.getDokumentum()).as("check dokumentum").isEqualTo(expected.getDokumentum()))
            .satisfies(a -> assertThat(a.getDokumentumUrl()).as("check dokumentumUrl").isEqualTo(expected.getDokumentumUrl()))
            .satisfies(a ->
                assertThat(a.getDokumentumAzonosito()).as("check dokumentumAzonosito").isEqualTo(expected.getDokumentumAzonosito())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegrendelesDokumentumokUpdatableRelationshipsEquals(
        MegrendelesDokumentumok expected,
        MegrendelesDokumentumok actual
    ) {
        assertThat(actual)
            .as("Verify MegrendelesDokumentumok relationships")
            .satisfies(a -> assertThat(a.getMegrendeles()).as("check megrendeles").isEqualTo(expected.getMegrendeles()));
    }
}
