package com.fintech.erp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OsztalekfizetesiKozgyulesekAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOsztalekfizetesiKozgyulesekAllPropertiesEquals(
        OsztalekfizetesiKozgyulesek expected,
        OsztalekfizetesiKozgyulesek actual
    ) {
        assertOsztalekfizetesiKozgyulesekAutoGeneratedPropertiesEquals(expected, actual);
        assertOsztalekfizetesiKozgyulesekAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOsztalekfizetesiKozgyulesekAllUpdatablePropertiesEquals(
        OsztalekfizetesiKozgyulesek expected,
        OsztalekfizetesiKozgyulesek actual
    ) {
        assertOsztalekfizetesiKozgyulesekUpdatableFieldsEquals(expected, actual);
        assertOsztalekfizetesiKozgyulesekUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOsztalekfizetesiKozgyulesekAutoGeneratedPropertiesEquals(
        OsztalekfizetesiKozgyulesek expected,
        OsztalekfizetesiKozgyulesek actual
    ) {
        assertThat(actual)
            .as("Verify OsztalekfizetesiKozgyulesek auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOsztalekfizetesiKozgyulesekUpdatableFieldsEquals(
        OsztalekfizetesiKozgyulesek expected,
        OsztalekfizetesiKozgyulesek actual
    ) {
        assertThat(actual)
            .as("Verify OsztalekfizetesiKozgyulesek relevant properties")
            .satisfies(a -> assertThat(a.getKozgyulesDatum()).as("check kozgyulesDatum").isEqualTo(expected.getKozgyulesDatum()))
            .satisfies(a ->
                assertThat(a.getKozgyulesiJegyzokonyvGeneralta())
                    .as("check kozgyulesiJegyzokonyvGeneralta")
                    .isEqualTo(expected.getKozgyulesiJegyzokonyvGeneralta())
            )
            .satisfies(a ->
                assertThat(a.getKozgyulesiJegyzokonyvAlairt())
                    .as("check kozgyulesiJegyzokonyvAlairt")
                    .isEqualTo(expected.getKozgyulesiJegyzokonyvAlairt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOsztalekfizetesiKozgyulesekUpdatableRelationshipsEquals(
        OsztalekfizetesiKozgyulesek expected,
        OsztalekfizetesiKozgyulesek actual
    ) {
        assertThat(actual)
            .as("Verify OsztalekfizetesiKozgyulesek relationships")
            .satisfies(a -> assertThat(a.getSajatCeg()).as("check sajatCeg").isEqualTo(expected.getSajatCeg()));
    }
}
