package com.fintech.erp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PartnerCegAdatokAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerCegAdatokAllPropertiesEquals(PartnerCegAdatok expected, PartnerCegAdatok actual) {
        assertPartnerCegAdatokAutoGeneratedPropertiesEquals(expected, actual);
        assertPartnerCegAdatokAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerCegAdatokAllUpdatablePropertiesEquals(PartnerCegAdatok expected, PartnerCegAdatok actual) {
        assertPartnerCegAdatokUpdatableFieldsEquals(expected, actual);
        assertPartnerCegAdatokUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerCegAdatokAutoGeneratedPropertiesEquals(PartnerCegAdatok expected, PartnerCegAdatok actual) {
        assertThat(actual)
            .as("Verify PartnerCegAdatok auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerCegAdatokUpdatableFieldsEquals(PartnerCegAdatok expected, PartnerCegAdatok actual) {
        assertThat(actual)
            .as("Verify PartnerCegAdatok relevant properties")
            .satisfies(a -> assertThat(a.getStatusz()).as("check statusz").isEqualTo(expected.getStatusz()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerCegAdatokUpdatableRelationshipsEquals(PartnerCegAdatok expected, PartnerCegAdatok actual) {
        assertThat(actual)
            .as("Verify PartnerCegAdatok relationships")
            .satisfies(a -> assertThat(a.getCeg()).as("check ceg").isEqualTo(expected.getCeg()));
    }
}
