package com.fintech.erp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PartnerCegKapcsolattartokAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerCegKapcsolattartokAllPropertiesEquals(
        PartnerCegKapcsolattartok expected,
        PartnerCegKapcsolattartok actual
    ) {
        assertPartnerCegKapcsolattartokAutoGeneratedPropertiesEquals(expected, actual);
        assertPartnerCegKapcsolattartokAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerCegKapcsolattartokAllUpdatablePropertiesEquals(
        PartnerCegKapcsolattartok expected,
        PartnerCegKapcsolattartok actual
    ) {
        assertPartnerCegKapcsolattartokUpdatableFieldsEquals(expected, actual);
        assertPartnerCegKapcsolattartokUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerCegKapcsolattartokAutoGeneratedPropertiesEquals(
        PartnerCegKapcsolattartok expected,
        PartnerCegKapcsolattartok actual
    ) {
        assertThat(actual)
            .as("Verify PartnerCegKapcsolattartok auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerCegKapcsolattartokUpdatableFieldsEquals(
        PartnerCegKapcsolattartok expected,
        PartnerCegKapcsolattartok actual
    ) {
        assertThat(actual)
            .as("Verify PartnerCegKapcsolattartok relevant properties")
            .satisfies(a ->
                assertThat(a.getKapcsolattartoTitulus()).as("check kapcsolattartoTitulus").isEqualTo(expected.getKapcsolattartoTitulus())
            )
            .satisfies(a -> assertThat(a.getStatusz()).as("check statusz").isEqualTo(expected.getStatusz()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerCegKapcsolattartokUpdatableRelationshipsEquals(
        PartnerCegKapcsolattartok expected,
        PartnerCegKapcsolattartok actual
    ) {
        assertThat(actual)
            .as("Verify PartnerCegKapcsolattartok relationships")
            .satisfies(a -> assertThat(a.getPartnerCeg()).as("check partnerCeg").isEqualTo(expected.getPartnerCeg()))
            .satisfies(a -> assertThat(a.getMaganszemely()).as("check maganszemely").isEqualTo(expected.getMaganszemely()));
    }
}
