package com.fintech.erp.domain;

import static com.fintech.erp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SajatCegAlapadatokAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegAlapadatokAllPropertiesEquals(SajatCegAlapadatok expected, SajatCegAlapadatok actual) {
        assertSajatCegAlapadatokAutoGeneratedPropertiesEquals(expected, actual);
        assertSajatCegAlapadatokAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegAlapadatokAllUpdatablePropertiesEquals(SajatCegAlapadatok expected, SajatCegAlapadatok actual) {
        assertSajatCegAlapadatokUpdatableFieldsEquals(expected, actual);
        assertSajatCegAlapadatokUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegAlapadatokAutoGeneratedPropertiesEquals(SajatCegAlapadatok expected, SajatCegAlapadatok actual) {
        assertThat(actual)
            .as("Verify SajatCegAlapadatok auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegAlapadatokUpdatableFieldsEquals(SajatCegAlapadatok expected, SajatCegAlapadatok actual) {
        assertThat(actual)
            .as("Verify SajatCegAlapadatok relevant properties")
            .satisfies(a ->
                assertThat(a.getCegAdminisztraciosHaviKoltseg())
                    .as("check cegAdminisztraciosHaviKoltseg")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCegAdminisztraciosHaviKoltseg())
            )
            .satisfies(a -> assertThat(a.getStatusz()).as("check statusz").isEqualTo(expected.getStatusz()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegAlapadatokUpdatableRelationshipsEquals(SajatCegAlapadatok expected, SajatCegAlapadatok actual) {
        assertThat(actual)
            .as("Verify SajatCegAlapadatok relationships")
            .satisfies(a -> assertThat(a.getCeg()).as("check ceg").isEqualTo(expected.getCeg()));
    }
}
