package com.fintech.erp.domain;

import static com.fintech.erp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SajatCegTulajdonosokAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegTulajdonosokAllPropertiesEquals(SajatCegTulajdonosok expected, SajatCegTulajdonosok actual) {
        assertSajatCegTulajdonosokAutoGeneratedPropertiesEquals(expected, actual);
        assertSajatCegTulajdonosokAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegTulajdonosokAllUpdatablePropertiesEquals(SajatCegTulajdonosok expected, SajatCegTulajdonosok actual) {
        assertSajatCegTulajdonosokUpdatableFieldsEquals(expected, actual);
        assertSajatCegTulajdonosokUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegTulajdonosokAutoGeneratedPropertiesEquals(SajatCegTulajdonosok expected, SajatCegTulajdonosok actual) {
        assertThat(actual)
            .as("Verify SajatCegTulajdonosok auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegTulajdonosokUpdatableFieldsEquals(SajatCegTulajdonosok expected, SajatCegTulajdonosok actual) {
        assertThat(actual)
            .as("Verify SajatCegTulajdonosok relevant properties")
            .satisfies(a ->
                assertThat(a.getBruttoOsztalek())
                    .as("check bruttoOsztalek")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBruttoOsztalek())
            )
            .satisfies(a -> assertThat(a.getStatusz()).as("check statusz").isEqualTo(expected.getStatusz()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegTulajdonosokUpdatableRelationshipsEquals(SajatCegTulajdonosok expected, SajatCegTulajdonosok actual) {
        assertThat(actual)
            .as("Verify SajatCegTulajdonosok relationships")
            .satisfies(a -> assertThat(a.getSajatCeg()).as("check sajatCeg").isEqualTo(expected.getSajatCeg()))
            .satisfies(a -> assertThat(a.getMaganszemely()).as("check maganszemely").isEqualTo(expected.getMaganszemely()));
    }
}
