package com.fintech.erp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SajatCegKepviselokAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegKepviselokAllPropertiesEquals(SajatCegKepviselok expected, SajatCegKepviselok actual) {
        assertSajatCegKepviselokAutoGeneratedPropertiesEquals(expected, actual);
        assertSajatCegKepviselokAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegKepviselokAllUpdatablePropertiesEquals(SajatCegKepviselok expected, SajatCegKepviselok actual) {
        assertSajatCegKepviselokUpdatableFieldsEquals(expected, actual);
        assertSajatCegKepviselokUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegKepviselokAutoGeneratedPropertiesEquals(SajatCegKepviselok expected, SajatCegKepviselok actual) {
        assertThat(actual)
            .as("Verify SajatCegKepviselok auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegKepviselokUpdatableFieldsEquals(SajatCegKepviselok expected, SajatCegKepviselok actual) {
        assertThat(actual)
            .as("Verify SajatCegKepviselok relevant properties")
            .satisfies(a -> assertThat(a.getStatusz()).as("check statusz").isEqualTo(expected.getStatusz()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSajatCegKepviselokUpdatableRelationshipsEquals(SajatCegKepviselok expected, SajatCegKepviselok actual) {
        assertThat(actual)
            .as("Verify SajatCegKepviselok relationships")
            .satisfies(a -> assertThat(a.getSajatCeg()).as("check sajatCeg").isEqualTo(expected.getSajatCeg()))
            .satisfies(a -> assertThat(a.getMaganszemely()).as("check maganszemely").isEqualTo(expected.getMaganszemely()));
    }
}
