package com.fintech.erp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TeljesitesIgazolasDokumentumokAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeljesitesIgazolasDokumentumokAllPropertiesEquals(
        TeljesitesIgazolasDokumentumok expected,
        TeljesitesIgazolasDokumentumok actual
    ) {
        assertTeljesitesIgazolasDokumentumokAutoGeneratedPropertiesEquals(expected, actual);
        assertTeljesitesIgazolasDokumentumokAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeljesitesIgazolasDokumentumokAllUpdatablePropertiesEquals(
        TeljesitesIgazolasDokumentumok expected,
        TeljesitesIgazolasDokumentumok actual
    ) {
        assertTeljesitesIgazolasDokumentumokUpdatableFieldsEquals(expected, actual);
        assertTeljesitesIgazolasDokumentumokUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeljesitesIgazolasDokumentumokAutoGeneratedPropertiesEquals(
        TeljesitesIgazolasDokumentumok expected,
        TeljesitesIgazolasDokumentumok actual
    ) {
        assertThat(actual)
            .as("Verify TeljesitesIgazolasDokumentumok auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeljesitesIgazolasDokumentumokUpdatableFieldsEquals(
        TeljesitesIgazolasDokumentumok expected,
        TeljesitesIgazolasDokumentumok actual
    ) {
        assertThat(actual)
            .as("Verify TeljesitesIgazolasDokumentumok relevant properties")
            .satisfies(a -> assertThat(a.getDokumentumTipusa()).as("check dokumentumTipusa").isEqualTo(expected.getDokumentumTipusa()))
            .satisfies(a -> assertThat(a.getDokumentum()).as("check dokumentum").isEqualTo(expected.getDokumentum()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeljesitesIgazolasDokumentumokUpdatableRelationshipsEquals(
        TeljesitesIgazolasDokumentumok expected,
        TeljesitesIgazolasDokumentumok actual
    ) {
        assertThat(actual)
            .as("Verify TeljesitesIgazolasDokumentumok relationships")
            .satisfies(a -> assertThat(a.getTeljesitesIgazolas()).as("check teljesitesIgazolas").isEqualTo(expected.getTeljesitesIgazolas())
            );
    }
}
