package com.fintech.erp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TimesheetekAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimesheetekAllPropertiesEquals(Timesheetek expected, Timesheetek actual) {
        assertTimesheetekAutoGeneratedPropertiesEquals(expected, actual);
        assertTimesheetekAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimesheetekAllUpdatablePropertiesEquals(Timesheetek expected, Timesheetek actual) {
        assertTimesheetekUpdatableFieldsEquals(expected, actual);
        assertTimesheetekUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimesheetekAutoGeneratedPropertiesEquals(Timesheetek expected, Timesheetek actual) {
        assertThat(actual)
            .as("Verify Timesheetek auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimesheetekUpdatableFieldsEquals(Timesheetek expected, Timesheetek actual) {
        assertThat(actual)
            .as("Verify Timesheetek relevant properties")
            .satisfies(a -> assertThat(a.getDatum()).as("check datum").isEqualTo(expected.getDatum()))
            .satisfies(a -> assertThat(a.getMunkanapStatusza()).as("check munkanapStatusza").isEqualTo(expected.getMunkanapStatusza()))
            .satisfies(a -> assertThat(a.getStatusz()).as("check statusz").isEqualTo(expected.getStatusz()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimesheetekUpdatableRelationshipsEquals(Timesheetek expected, Timesheetek actual) {
        assertThat(actual)
            .as("Verify Timesheetek relationships")
            .satisfies(a -> assertThat(a.getMunkavallalo()).as("check munkavallalo").isEqualTo(expected.getMunkavallalo()));
    }
}
