version: '3.8'

services:
  app:
    image: fintecherp:latest
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://185.65.68.120:32768/fintechErp
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://185.65.68.120:32768/fintechErp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresfintech!
      - SPRING_LIQUIBASE_USER=postgres
      - SPRING_LIQUIBASE_PASSWORD=postgresfintech!
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
    ports:
      - '8080:8080'
    depends_on:
      - keycloak
    networks:
      - fintecherp-net

  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
    networks:
      - fintecherp-net

networks:
  fintecherp-net:
    external: false
